### PR TITLE
created server.js w/ copy pasted orm.js/connection.js/

### PR DESCRIPTION
**Pull request by jihoshin28**
Created functional server.js file. Templates of orm.js, connection.js, controller, models files available.

### CODE REVIEW

**Comment by vnguyen1m** [comment]
Burgers doesn't go well with Lemonade. Redo!

**Review by ghost — CHANGES_REQUESTED** [review]
Please change 'burgers' to 'lemonade'

**Comment by vnguyen1m** [comment]
No Burgers please

**Comment by vnguyen1m** [comment]
No burgers please

**Pull request closed without merging**
